name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天00:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Sync upstream
      run: |
        git config --global user.email "itsaquestion@gmail.com"
        git config --global user.name "itsaquestion"
        git remote add upstream https://github.com/enricoros/big-AGI.git
        git fetch upstream
        git merge upstream/main --no-commit --no-ff
        git push
